import Provider from '../models/Provider.js';
async function providerForUser(user) { let provider = await Provider.findOne({ user: user.id }); if (!provider) { provider = await Provider.findOne({ name: user.name }); if (provider) { provider.user = user.id; await provider.save(); } } if (!provider) provider = await Provider.create({ user: user.id, name: user.name, initials: user.name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase(), specialty: 'Home services provider', location: 'Service area', isActive: true }); return provider; }
export async function listProviders(req, res) { const filter = req.query.skill ? { skills: req.query.skill } : {}; if (req.user.role === 'customer') filter.isActive = true; res.json(await Provider.find(filter).sort({ verified: -1, rating: -1 })); }
export async function getProvider(req, res) { const provider = await Provider.findById(req.params.id); if (!provider) return res.status(404).json({ message: 'Provider not found' }); res.json(provider); }
export async function getMyProvider(req, res) { res.json(await providerForUser(req.user)); }
export async function createProvider(req, res) { res.status(201).json(await Provider.create(req.body)); }
export async function updateProvider(req, res) { const updates = { ...req.body }; if (req.user.role === 'admin') delete updates.isActive; const provider = await Provider.findByIdAndUpdate(req.params.id, updates, { new: true, runValidators: true }); if (!provider) return res.status(404).json({ message: 'Provider not found' }); res.json(provider); }
export async function updateProviderActivity(req, res) { const filter = req.user.role === 'admin' ? { _id: req.params.id } : { _id: req.params.id, user: req.user.id }; const provider = await Provider.findOneAndUpdate(filter, { isActive: Boolean(req.body.isActive) }, { new: true, runValidators: true }); if (!provider) return res.status(404).json({ message: 'Provider profile not found for this account' }); res.json(provider); }
export async function updateMyProviderActivity(req, res) { const provider = await providerForUser(req.user); provider.isActive = Boolean(req.body.isActive); await provider.save(); res.json(provider); }
export async function updateMyProviderLocation(req, res) { const provider = await providerForUser(req.user); const lat = Number(req.body.lat); const lng = Number(req.body.lng); if (!Number.isFinite(lat) || !Number.isFinite(lng) || lat < -90 || lat > 90 || lng < -180 || lng > 180) return res.status(400).json({ message: 'Valid location coordinates are required' }); provider.locationCoordinates = { lat, lng }; await provider.save(); res.json(provider); }
export async function createProviderFromUser(req, res) { const user = await (await import('../models/User.js')).default.findById(req.params.userId); if (!user) return res.status(404).json({ message: 'User not found' }); const existing = await Provider.findOne({ user: user._id }); if (existing) return res.status(409).json({ message: 'Provider profile already exists' }); const provider = await Provider.create({ user: user._id, name: user.name, initials: user.name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase(), specialty: req.body.specialty || 'Home services provider', location: req.body.location || 'Service area', skills: req.body.skills || [], verified: false }); res.status(201).json(provider); }
