import ServiceRequest from '../models/ServiceRequest.js';
import Provider from '../models/Provider.js';
import Notification from '../models/Notification.js';
import User from '../models/User.js';
export async function listRequests(req, res) { let filter = req.user.role === 'customer' ? { customer: req.user.id } : {}; if (req.user.role === 'service_provider') { const provider = await Provider.findOne({ user: req.user.id }); filter = { provider: provider?._id || null }; } res.json(await ServiceRequest.find(filter).populate('provider', 'name initials rating specialty location locationCoordinates').populate('customer', 'name email').sort({ createdAt: -1 })); }
export async function createRequest(req, res) { try { const request = await ServiceRequest.create({ ...req.body, customer: req.user.id, status: 'Matching' }); const providerUsers = await User.find({ role: 'service_provider' }).select('_id name'); const providers = await Promise.all(providerUsers.map(async user => Provider.findOneAndUpdate({ user: user._id }, { $setOnInsert: { user: user._id, name: user.name, initials: user.name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase(), specialty: 'Home services provider', location: 'Service area', isActive: false } }, { upsert: true, new: true }))); if (providers.length) await Notification.insertMany(providers.map(provider => ({ provider: provider._id, request: request._id }))); res.status(201).json(request); } catch (error) { console.error('createRequest failed', error); res.status(error.name === 'ValidationError' ? 400 : 500).json({ message: error.message || 'Failed to create service request' }); } }
export async function updateRequestStatus(req, res) { const request = await ServiceRequest.findByIdAndUpdate(req.params.id, { status: req.body.status }, { new: true, runValidators: true }); if (!request) return res.status(404).json({ message: 'Request not found' }); res.json(request); }
export async function assignProvider(req, res) { const request = await ServiceRequest.findOne({ _id: req.params.id, customer: req.user.id }); if (!request) return res.status(404).json({ message: 'Request not found' }); const provider = await Provider.findOneAndUpdate({ _id: req.body.providerId, isActive: true }, { isActive: false }, { new: true }); if (!provider) return res.status(400).json({ message: 'This provider is not currently active' }); request.provider = provider._id; request.status = 'Scheduled'; await request.save(); res.json(await request.populate('provider', 'name initials rating specialty isActive')); }
export async function completeRequest(req, res) { const filter = req.user.role === 'admin' ? { _id: req.params.id } : { _id: req.params.id, customer: req.user.id }; const request = await ServiceRequest.findOne(filter).populate('provider'); if (!request) return res.status(404).json({ message: 'Request not found' }); if (!request.provider) return res.status(400).json({ message: 'No provider is assigned to this request' }); request.status = 'Completed'; request.customerLocation = undefined; await request.save(); await request.populate([{ path: 'provider', select: 'name initials rating specialty location locationCoordinates' }, { path: 'customer', select: 'name email' }]); res.json(request); }
