import { useEffect, useState } from 'react';
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { Activity, CalendarDays, CheckCircle2, ClipboardList, Home, LifeBuoy, LogOut, Plus, ShieldCheck, Sparkles, UserRound, Users, Wrench } from 'lucide-react';
import { AuthProvider, useAuth } from './context/AuthContext.jsx';
import ProtectedRoute from './components/ProtectedRoute.jsx';
import { providerApi, requestApi } from './services/api.js';
import './styles.css';

const roleNames = { admin: 'Platform Admin', user: 'Customer', operation: 'Operations', operation_manager: 'Operations Manager', service_provider: 'Service Provider', support_agent: 'Support Agent' };
const roleLinks = { admin: [['Overview', '/', Home], ['Users & roles', '/users', Users], ['Providers', '/providers', Wrench], ['Requests', '/requests', ClipboardList]], user: [['My requests', '/', ClipboardList], ['Find providers', '/providers', Users], ['Bookings', '/bookings', CalendarDays]], operation: [['Operations board', '/', Activity], ['Bookings', '/bookings', CalendarDays], ['Requests', '/requests', ClipboardList]], operation_manager: [['Operations board', '/', Activity], ['Bookings', '/bookings', CalendarDays], ['Quality', '/quality', ShieldCheck]], service_provider: [['My jobs', '/', ClipboardList], ['Availability', '/availability', CalendarDays], ['Profile', '/profile', UserRound]], support_agent: [['Support inbox', '/', LifeBuoy], ['Disputes', '/disputes', ShieldCheck], ['Requests', '/requests', ClipboardList]] };
function Shell() { const { user, signOut } = useAuth(); const location = useLocation(); const navigate = useNavigate(); const links = roleLinks[user.role] || roleLinks.user; return <div className="role-shell"><aside className="role-sidebar"><div className="role-brand"><span><Sparkles size={15}/></span>careconnect</div><div className="role-label">YOUR WORKSPACE</div><div className="role-card"><div className="role-avatar">{user.name.slice(0, 2).toUpperCase()}</div><div><strong>{user.name}</strong><small>{roleNames[user.role]}</small></div></div><nav>{links.map(([label, path, Icon]) => <Link className={location.pathname === path ? 'role-link active' : 'role-link'} to={path} key={path + label}><Icon size={17}/>{label}</Link>)}</nav><button className="signout" onClick={() => { signOut(); navigate('/login'); }}><LogOut size={17}/> Sign out</button></aside><main className="role-main"><header className="role-header"><div><span className="role-kicker">CARECONNECT / {roleNames[user.role].toUpperCase()}</span><h1>{roleNames[user.role]} workspace</h1></div><div className="role-user">{user.name}<span>{user.email}</span></div></header><div className="role-content"><Routes><Route path="/" element={<RoleHome/>}/><Route path="/providers" element={<Providers/>}/><Route path="/requests" element={<Requests/>}/><Route path="/users" element={<AdminUsers/>}/><Route path="*" element={<RoleHome/>}/></Routes></div></main></div> }
function RoleHome() { const { user } = useAuth(); const isCustomer = user.role === 'user'; const [open, setOpen] = useState(false); return <><div className="role-intro"><div><p className="role-kicker">TODAY'S WORK</p><h2>{isCustomer ? 'What can we help with?' : 'Your team at a glance'}</h2><p>{isCustomer ? 'Book a trusted local professional in a few simple steps.' : `Manage ${roleNames[user.role].toLowerCase()} work from one place.`}</p></div>{isCustomer && <button className="role-primary" onClick={() => setOpen(true)}><Plus size={17}/> New request</button>}</div><div className="role-stats"><Metric label={isCustomer ? 'Open requests' : 'Active work'} value={isCustomer ? '3' : '24'} icon={ClipboardList}/><Metric label="Scheduled" value="8" icon={CalendarDays}/><Metric label={isCustomer ? 'Quotes received' : 'Resolution rate'} value={isCustomer ? '11' : '92%'} icon={CheckCircle2}/></div>{open && <NewRequest onClose={() => setOpen(false)}/>}<div className="role-panel"><h3>{isCustomer ? 'Recent requests' : 'Priority queue'}</h3><Requests compact/></div></> }
function Metric({ label, value, icon: Icon }) { return <div className="role-metric"><Icon size={19}/><span>{label}</span><strong>{value}</strong></div> }
function Requests({ compact = false }) { const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); useEffect(() => { requestApi.list().then(setItems).catch(() => setItems([])).finally(() => setLoading(false)); }, []); return <div className="data-list">{loading ? <p>Loading requests...</p> : items.length ? items.slice(0, compact ? 5 : 20).map(item => <div className="data-row" key={item._id}><div><strong>{item.title}</strong><small>{item.category} · {item.address}</small></div><span className="data-status">{item.status}</span></div>) : <p>No requests yet. Create the first service request from your workspace.</p>}</div> }
function Providers() { const [items, setItems] = useState([]); useEffect(() => { providerApi.list().then(setItems).catch(() => setItems([])); }, []); return <div className="role-panel"><div className="panel-title"><div><h3>Verified providers</h3><p>Browse trusted professionals by rating and skill.</p></div></div><div className="data-list">{items.length ? items.map(item => <div className="data-row" key={item._id}><div><strong>{item.name} {item.verified && <CheckCircle2 size={14}/>}</strong><small>{item.specialty} · {item.location}</small></div><span className="data-rating">★ {item.rating || 'New'}</span></div>) : <p>No providers found yet.</p>}</div></div> }
function AdminUsers() { const [users, setUsers] = useState([]); const roles = Object.keys(roleNames); useEffect(() => { import('./services/api.js').then(({ apiRequest }) => apiRequest('/users')).then(setUsers).catch(() => setUsers([])); }, []); const changeRole = async (id, role) => { const { apiRequest } = await import('./services/api.js'); const updated = await apiRequest(`/users/${id}/role`, { method: 'PATCH', body: JSON.stringify({ role }) }); setUsers(users.map(item => item._id === id ? updated : item)); }; return <div className="role-panel"><div className="panel-title"><div><h3>Users & role access</h3><p>Only administrators can change access levels.</p></div></div><div className="data-list">{users.map(item => <div className="data-row" key={item._id}><div><strong>{item.name}</strong><small>{item.email}</small></div><select value={item.role} onChange={event => changeRole(item._id, event.target.value)}>{roles.map(role => <option value={role} key={role}>{roleNames[role]}</option>)}</select></div>)}</div></div> }
function NewRequest({ onClose }) { const [error, setError] = useState(''); const submit = async event => { event.preventDefault(); try { await requestApi.create(Object.fromEntries(new FormData(event.currentTarget))); onClose(); window.location.reload(); } catch (requestError) { setError(requestError.message); } }; return <div className="dialog-backdrop"><form className="dialog" onSubmit={submit}><h3>New service request</h3><input name="title" placeholder="What needs fixing?" required/><select name="category"><option>Appliance repair</option><option>Cleaning</option><option>Electrical</option><option>Plumbing</option><option>Maintenance</option></select><input name="address" placeholder="Service address" required/><textarea name="description" placeholder="Describe the job" rows="3"/><button className="role-primary" type="submit">Find providers</button>{error && <p className="form-error">{error}</p>}<button className="dialog-close" type="button" onClick={onClose}>Cancel</button></form></div> }
function Login({ register = false }) { const { signIn } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const submit = async event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const result = register ? await (await import('./services/api.js')).authApi.register(values) : await signIn(values); if (register) { sessionStorage.setItem('careconnect_token', result.token); sessionStorage.setItem('careconnect_user', JSON.stringify(result.user)); } navigate('/'); } catch (loginError) { setError(loginError.message); } }; return <main className="auth-page"><form className="auth-card" onSubmit={submit}><div className="role-brand"><span><Sparkles size={15}/></span>careconnect</div><h1>{register ? 'Create your account' : 'Welcome back'}</h1><p>{register ? 'Start booking trusted home services.' : 'Sign in to your service workspace.'}</p>{register && <input name="name" placeholder="Full name" required/>}<input name="email" type="email" placeholder="Email address" required/><input name="password" type="password" placeholder="Password" required/><button className="role-primary" type="submit">{register ? 'Create account' : 'Sign in'}</button>{error && <p className="form-error">{error}</p>}<Link to={register ? '/login' : '/register'}>{register ? 'Already have an account? Sign in' : 'Create a customer account'}</Link></form></main> }
function AppRoutes() { const { user } = useAuth(); return <Routes><Route path="/login" element={user ? <Navigate to="/"/> : <Login/>}/><Route path="/register" element={user ? <Navigate to="/"/> : <Login register/>}/><Route path="/*" element={<ProtectedRoute><Shell/></ProtectedRoute>}/></Routes> }
export default function App() { return <BrowserRouter><AuthProvider><AppRoutes/></AuthProvider></BrowserRouter>; }
