import React, { useEffect, useState } from 'react';
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { Bot, CheckCircle2, Home, LogOut, MessageCircle, Plus, Sparkles, Wrench } from 'lucide-react';
import { AuthProvider, useAuth } from './context/AuthContext.jsx';
import ProtectedRoute from './components/ProtectedRoute.jsx';
import ServiceMap from './components/ServiceMap.jsx';
import { apiRequest, notificationApi, providerApi, requestApi } from './services/api.js';
import './role.css';
import './tailwind.css';
import './workspace.css';
import './blue-theme.css';
import './dark-ui.css';

const roles = {
  admin: { label: 'Platform Admin', links: [['Overview', '/admin', Home]] },
  customer: { label: 'Customer', links: [['My requests', '/customer', Home], ['Support inbox', '/support', MessageCircle]] },
  service_provider: { label: 'Service Provider', links: [['My jobs', '/service_provider', Wrench]] }
};

function Shell() {
  const { user, signOut } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();
  const role = roles[user.role] || roles.customer;
  return <div className="role-shell"><aside className="role-sidebar"><div className="role-brand"><span><Sparkles size={15} /></span>careconnect</div><p className="role-label">{role.label.toUpperCase()}</p><div className="role-card"><div className="role-avatar">{user.name.slice(0, 2).toUpperCase()}</div><div><strong>{user.name}</strong><small>{role.label}</small></div></div><nav>{role.links.map(([label, path, Icon]) => <Link className={location.pathname === path ? 'role-link active' : 'role-link'} to={path} key={path}><Icon size={17} />{label}</Link>)}</nav><button className="signout" onClick={() => { signOut(); navigate('/login'); }}><LogOut size={17} />Sign out</button></aside><main className="role-main"><header className="role-header"><div><span className="role-kicker">CAreCONNECT / {role.label.toUpperCase()}</span><h1>{role.label} dashboard</h1></div><div className="role-user">{user.name}<span>{user.email}</span></div></header><div className="role-content"><Routes><Route path="/admin" element={<RoleHome />} /><Route path="/customer" element={<RoleHome />} /><Route path="/service_provider" element={<RoleHome />} /><Route path="/providers" element={<ProvidersPage />} /><Route path="/support" element={<SupportPage />} /><Route path="*" element={<RoleHome />} /></Routes></div></main></div>;
}

function RoleHome() {
  const { user } = useAuth();
  const [open, setOpen] = useState(false);
  if (user.role === 'admin') return <AdminHome />;
  const provider = user.role === 'service_provider';
  return <><div className="role-intro"><div><span className="role-kicker">{roles[user.role].label.toUpperCase()}</span><h2>{provider ? 'Manage your service work.' : 'What can we help with?'}</h2><p>{provider ? 'Review service requests from available customers.' : 'Tell us what needs fixing and available providers can accept it.'}</p></div><img className="dashboard-photo" src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=420&q=80" alt="Home service professional at work" />{!provider && <button className="role-primary" onClick={() => setOpen(true)}><Plus size={17} />Book a service</button>}</div>{open && <NewRequest onClose={() => setOpen(false)} />}{provider && <ProviderNotifications />}<div className="role-panel"><h3>{provider ? 'Accepted service requests' : 'My service requests'}</h3><RequestList /></div></>;
}
function AdminHome() { const [stats, setStats] = useState({ totalCustomers: 0, totalProviders: 0 }); useEffect(() => { apiRequest('/analytics/overview').then(setStats).catch(() => {}); }, []); return <><div className="role-intro"><div><span className="role-kicker">PLATFORM ADMIN</span><h2>Network overview</h2><p>Use Providers to activate or deactivate service professionals.</p></div></div><div className="role-stats"><Metric label="Customers" value={stats.totalCustomers} /><Metric label="Service providers" value={stats.totalProviders} /></div><div className="role-panel"><h3>All service requests</h3><RequestList /></div></>; }
function Metric({ label, value }) { return <div className="role-metric"><CheckCircle2 size={18} /><span>{label}</span><strong>{value}</strong></div>; }
function RequestList() { const { user } = useAuth(); const [items, setItems] = useState([]); const [message, setMessage] = useState(''); const load = () => requestApi.list().then(setItems).catch(() => setItems([])); useEffect(() => { load(); const refresh = setInterval(load, 5000); return () => clearInterval(refresh); }, []); const complete = async id => { try { await requestApi.complete(id); setMessage('Service marked completed. The route map has been removed.'); load(); } catch (error) { setMessage(error.message); } }; return <div className="data-list">{message && <p className="form-success"><CheckCircle2 size={16} />{message}</p>}{items.length ? items.map(item => <div className={item.provider ? 'data-row accepted-request' : 'data-row'} key={item._id}><div><strong>{item.title} {item.provider && <CheckCircle2 className="assigned-mark" size={14} />}</strong><small>{item.category} · {item.address}</small>{item.customer && <div className="accepted-provider"><strong>Customer booking</strong><span>{item.customer.name}</span><small>{item.customer.email}</small></div>}{item.provider && <div className="accepted-provider"><strong>Provider accepted</strong><span>{item.provider.name}</span><small>{item.provider.specialty}{item.provider.rating ? ` · Rating ${item.provider.rating}` : ''}{item.provider.location ? ` · ${item.provider.location}` : ''}</small></div>}{item.provider && item.customerLocation && <ServiceMap request={item} providerView={user.role === 'service_provider'} />}</div><div className="request-actions"><span className="data-status">{item.status}</span>{(user.role === 'customer' || user.role === 'admin') && item.provider && ['Scheduled', 'In progress'].includes(item.status) && <button className="complete-button" onClick={() => complete(item._id)}>Completed</button>}</div></div>) : <p>No service requests yet.</p>}</div>; }
function ProviderNotifications() { const [items, setItems] = useState([]); const [message, setMessage] = useState(''); const load = () => notificationApi.list().then(setItems).catch(() => setItems([])); useEffect(() => { load(); const refresh = setInterval(load, 5000); return () => clearInterval(refresh); }, []); const accept = async id => { try { await notificationApi.accept(id); setMessage('Request accepted. The customer can now see your provider details.'); load(); } catch (error) { setMessage(error.message); } }; const reject = async id => { try { await notificationApi.reject(id); setMessage('Request rejected.'); load(); } catch (error) { setMessage(error.message); } }; return <div className="role-panel"><h3>New service requests</h3>{message && <p className="form-success"><CheckCircle2 size={16} />{message}</p>}<div className="data-list">{items.length ? items.map(item => <div className="data-row notification-row" key={item._id}><div><strong>{item.request.title}</strong><small>{item.request.category} · {item.request.address}</small><small>Customer: {item.request.customer?.name || 'Customer'}</small></div><div className="notification-actions"><button className="role-primary accept-button" onClick={() => accept(item._id)}>Accept request</button><button className="role-secondary reject-button" onClick={() => reject(item._id)}>Reject</button></div></div>) : <p>No new service requests.</p>}</div></div>; }
function ProvidersPage() { const { user } = useAuth(); const [items, setItems] = useState([]); useEffect(() => { providerApi.list().then(setItems).catch(() => setItems([])); }, []); return <div className="role-panel"><div className="data-list">{items.length ? items.map(item => <div className="data-row" key={item._id}><div><strong>{item.name} {item.isActive && <CheckCircle2 size={14} />}</strong><small>{item.specialty} · {item.location}</small></div><span className="data-status">{user.role === 'customer' || item.isActive ? 'Active' : 'Unavailable'}</span></div>) : <p>{user.role === 'customer' ? 'No active providers are available yet.' : 'No provider profiles found.'}</p>}</div></div>; }
function CustomerProviderPicker({ providers, setMessage }) { const [requests, setRequests] = useState([]); const [assigned, setAssigned] = useState({}); const active = providers.filter(item => item.isActive); useEffect(() => { requestApi.list().then(setRequests).catch(() => setRequests([])); }, []); const assign = async (requestId, providerId) => { try { const updated = await requestApi.assign(requestId, providerId); setAssigned(current => ({ ...current, [requestId]: updated.provider?.name || 'Provider' })); setRequests(current => current.map(request => request._id === requestId ? updated : request)); setMessage({ type: 'success', text: 'Provider assigned successfully. Your service is scheduled.' }); } catch (error) { setMessage({ type: 'error', text: error.message }); } }; const unassigned = requests.filter(item => !item.provider && !assigned[item._id] && !['Completed', 'Cancelled'].includes(item.status)); return unassigned.length && active.length ? <div className="picker"><h3>Select a provider</h3>{unassigned.map(request => <div className="data-row" key={request._id}><span>{request.title}</span><select defaultValue="" onChange={event => event.target.value && assign(request._id, event.target.value)}><option value="">Choose active provider</option>{active.map(provider => <option value={provider._id} key={provider._id}>{provider.name} · {provider.specialty}</option>)}</select></div>)}</div> : null; }
function UsersPage() { const [items, setItems] = useState([]); useEffect(() => { apiRequest('/users').then(setItems).catch(() => setItems([])); }, []); const changeRole = async (id, role) => { const updated = await apiRequest(`/users/${id}/role`, { method: 'PATCH', body: JSON.stringify({ role }) }); setItems(current => current.map(item => item._id === id ? updated : item)); }; return <div className="role-panel"><h3>Users and providers</h3><div className="data-list">{items.map(item => <div className="data-row" key={item._id}><div><strong>{item.name}</strong><small>{item.email}</small></div><select value={item.role} onChange={event => changeRole(item._id, event.target.value)}>{Object.entries(roles).map(([value, info]) => <option value={value} key={value}>{info.label}</option>)}</select></div>)}</div></div>; }
function SupportPage() { const [messages, setMessages] = useState([{ from: 'bot', text: 'Hi. I can help with booking, cancelling, provider selection, and service status.' }]); const [input, setInput] = useState(''); const send = event => { event.preventDefault(); const question = input.trim(); if (!question) return; const lower = question.toLowerCase(); const answer = lower.includes('cancel') ? 'Open My requests and contact support with the request title.' : lower.includes('book') || lower.includes('provider') ? 'Create a service booking and providers will receive it.' : lower.includes('status') ? 'Scheduled means a provider has been selected for your request.' : 'I can answer questions about booking, cancellation, providers, and request status.'; setMessages(current => [...current, { from: 'user', text: question }, { from: 'bot', text: answer }]); setInput(''); }; return <div className="role-panel chat-panel"><h3><Bot size={18} /> CareConnect support</h3><div className="chat-messages">{messages.map((message, index) => <p className={message.from} key={index}>{message.text}</p>)}</div><form onSubmit={send} className="chat-form"><input value={input} onChange={event => setInput(event.target.value)} placeholder="Ask about booking or cancelling" /><button className="role-primary" type="submit"><MessageCircle size={16} />Send</button></form></div>; }
function NewRequest({ onClose }) { const [error, setError] = useState(''); const [location, setLocation] = useState(null); const captureLocation = () => navigator.geolocation?.getCurrentPosition(position => setLocation({ lat: position.coords.latitude, lng: position.coords.longitude }), () => setError('Location permission is needed for live route tracking.')); const submit = async event => { event.preventDefault(); try { const details = Object.fromEntries(new FormData(event.currentTarget)); if (location) details.customerLocation = location; await requestApi.create(details); onClose(); window.location.reload(); } catch (requestError) { setError(requestError.message); } }; return <div className="dialog-backdrop"><form className="dialog" onSubmit={submit}><h3>New service request</h3><input name="title" placeholder="What needs fixing?" required /><select name="category"><option>Appliance repair</option><option>Cleaning</option><option>Electrical</option><option>Plumbing</option><option>Maintenance</option></select><input name="address" placeholder="Service address" required /><textarea name="description" placeholder="Describe the job" rows="3" /><button className="role-secondary" type="button" onClick={captureLocation}>{location ? 'Location attached' : 'Share my location'}</button><button className="role-primary" type="submit">Create request</button><button className="dialog-close" type="button" onClick={onClose}>Cancel</button>{error && <p className="form-error">{error}</p>}</form></div>; }
function AuthPage({ register = false }) { const { signIn, register: createAccount, signOut } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const submit = async event => { event.preventDefault(); try { const session = register ? await createAccount(Object.fromEntries(new FormData(event.currentTarget))) : await signIn(Object.fromEntries(new FormData(event.currentTarget))); if (register) { signOut(); navigate('/login'); } else { navigate(session.role === 'admin' ? '/admin' : `/${session.role}`); } } catch (authError) { setError(authError.message); } }; const goToLogin = event => { event.preventDefault(); signOut(); navigate('/login'); }; return <main className="auth-page"><form className="auth-card" onSubmit={submit}><div className="role-brand"><span><Sparkles size={15} /></span>careconnect</div><h1>{register ? 'Create your account' : 'Welcome back'}</h1><p>{register ? 'Choose a customer or provider workspace.' : 'Sign in to your service workspace.'}</p>{register && <input name="name" placeholder="Full name" required />}<input name="email" type="email" placeholder="Email address" required /><input name="password" type="password" placeholder="Password" minLength="6" required />{register && <select name="role" defaultValue="customer" required><option value="customer">Customer</option><option value="service_provider">Service Provider</option></select>}<button className="role-primary" type="submit">{register ? 'Create account' : 'Sign in'}</button>{error && <p className="form-error">{error}</p>}<Link to={register ? '/login' : '/register'} onClick={register ? goToLogin : undefined}>{register ? 'Already registered? Sign in' : 'Create an account'}</Link></form></main>; }
function AppRoutes() { const { user } = useAuth(); const destination = user ? (user.role === 'admin' ? '/admin' : `/${user.role}`) : '/login'; return <Routes><Route path="/" element={user ? <Navigate to={destination} replace /> : <AuthPage />} /><Route path="/login" element={<AuthPage />} /><Route path="/register" element={<AuthPage register />} /><Route path="/admin/*" element={<ProtectedRoute roles={['admin']}><Shell /></ProtectedRoute>} /><Route path="/customer/*" element={<ProtectedRoute roles={['customer']}><Shell /></ProtectedRoute>} /><Route path="/service_provider/*" element={<ProtectedRoute roles={['service_provider']}><Shell /></ProtectedRoute>} /><Route path="/*" element={<ProtectedRoute><Shell /></ProtectedRoute>} /></Routes>; }
export default function RoleApp() { return <BrowserRouter><AuthProvider><AppRoutes /></AuthProvider></BrowserRouter>; }
